common:
  server:
    name: analysis
    runmode: debug
    addr: www.laiys.com:443
    tls: false
    tlspem: ./cert/www.laiys.com.pem
    tlskey: ./cert/www.laiys.com.key
  kafka:
    addr: 192.168.127.160:9092
    topic: weblog